### ISSUE TITLE
Feature Request: Add optional verbose flag to control screen output in max_orthogonality

### ISSUE THREAD

**Issue by Lucandia** [storyetfall/seqwalk#2]
Hi,

First of all, thank you very much for developing and sharing this project! I think it's super cool and works very well.

I'd like to import and use the function `max_orthogonality` in my Python scripts, but I noticed that it always prints the "Attempting SSM k values" and the number of sequences to the screen. 

Would it be possible to make this optional? Perhaps by adding an argument like `verbose=True` that could be turned off to suppress the output? I think this would make the function more flexible, especially when used in scripts where print statements aren't needed.

Additionally, I don't particularly need the k-value that is printed to the screen, but it might be useful to have it as an optional return value. Maybe an additional argument could be used to select whether to return the k-value alongside the library.

These should be relatively simple features to implement, and I'd be happy to contribute if you'd like. Let me know your thoughts!

Thanks again!

**Comment by g-kl** [comment]
Hi Luca,

Thanks so much for reaching out, and happy to hear that you find the tool useful.

Having a verbosity argument is sensible, and I should have written it that way the first time. If you submit a PR, I'd be grateful and happy to merge+rerelease. Otherwise, I will put this on my to-do list and get to it eventually, but likely more slowly.

In the meantime, one possibility if you're in a Jupyter notebook is to use the `%%capture` cell tag to hide the print. There is surely some other hack that can work in a script, but I don't know off the top of my head.

gokul

**Comment by g-kl** [comment]
Thanks for contributing Luca! Merged and will rerelease tomorrow.
